# Generated by Django 5.1.3 on 2024-12-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_alter_pin_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pin",
            name="user",
        ),
    ]
