# Generated by Django 5.1.2 on 2024-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instalink',
            new_name='insta_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedinlink',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='otherlink',
            new_name='other_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phoneno',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileid',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitterlink',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
