# Generated by Django 5.1.3 on 2024-12-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
