# Generated by Django 5.1.3 on 2024-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_age_remove_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_domain',
            field=models.CharField(choices=[('ai_ml', 'Artificial Intelligence & Machine Learning'), ('AI/ML', 'Artificial Intelligence & Machine Learning'), ('data_science', 'Data Science'), ('cyber_security', 'Cyber Security'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('ux_ui', 'User Experience & User Interface Design'), ('cloud_computing', 'Cloud Computing'), ('blockchain', 'Blockchain Technology'), ('digital_marketing', 'Digital Marketing'), ('fintech', 'Financial Technology'), ('healthtech', 'Health Technology')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='domain_of_interest',
            field=models.CharField(blank=True, choices=[('ai_ml', 'Artificial Intelligence & Machine Learning'), ('AI/ML', 'Artificial Intelligence & Machine Learning'), ('data_science', 'Data Science'), ('cyber_security', 'Cyber Security'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('ux_ui', 'User Experience & User Interface Design'), ('cloud_computing', 'Cloud Computing'), ('blockchain', 'Blockchain Technology'), ('digital_marketing', 'Digital Marketing'), ('fintech', 'Financial Technology'), ('healthtech', 'Health Technology')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(max_length=50, null=True),
        ),
    ]
