# Generated by Django 5.1.3 on 2024-11-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_job_job_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
    ]
