# Generated by Django 5.1.2 on 2024-11-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_job_job_domain_job_job_type_job_skills_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_domain',
            field=models.CharField(choices=[('ai_ml', 'Artificial Intelligence & Machine Learning'), ('data_science', 'Data Science'), ('cyber_security', 'Cyber Security'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('ux_ui', 'User Experience & User Interface Design'), ('cloud_computing', 'Cloud Computing'), ('blockchain', 'Blockchain Technology'), ('digital_marketing', 'Digital Marketing'), ('fintech', 'Financial Technology'), ('healthtech', 'Health Technology')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], max_length=30),
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_by', to='myapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='myapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
