# Generated by Django 5.1.3 on 2024-11-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
    ]
